openapi: 3.2.0
info:
  title: NovelAI Primary / API
  description: The Primary API describes actions that our Frontend makes against the NovelAI backend.
  version: '1.0'
  contact: {}
servers:
- url: https://api.novelai.net
  description: NovelAI Primary API
tags:
- name: /
paths:
  /:
    get:
      operationId: AppController_healthCheck
      parameters: []
      responses:
        '200':
          description: Everything is running fine.
      tags:
      - /
      summary: App controller health check
      x-summary-source: derived
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
